# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IngestSegment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IngestSegment.proto',
  package='com.blackfynn.streaming',
  syntax='proto3',
  serialized_pb=_b('\n\x13IngestSegment.proto\x12\x17\x63om.blackfynn.streaming\"Y\n\rIngestSegment\x12\x11\n\tchannelId\x18\x01 \x01(\t\x12\x11\n\tstartTime\x18\x02 \x01(\x04\x12\x14\n\x0csamplePeriod\x18\x03 \x01(\x01\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INGESTSEGMENT = _descriptor.Descriptor(
  name='IngestSegment',
  full_name='com.blackfynn.streaming.IngestSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channelId', full_name='com.blackfynn.streaming.IngestSegment.channelId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='com.blackfynn.streaming.IngestSegment.startTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samplePeriod', full_name='com.blackfynn.streaming.IngestSegment.samplePeriod', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.blackfynn.streaming.IngestSegment.data', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['IngestSegment'] = _INGESTSEGMENT

IngestSegment = _reflection.GeneratedProtocolMessageType('IngestSegment', (_message.Message,), dict(
  DESCRIPTOR = _INGESTSEGMENT,
  __module__ = 'IngestSegment_pb2'
  # @@protoc_insertion_point(class_scope:com.blackfynn.streaming.IngestSegment)
  ))
_sym_db.RegisterMessage(IngestSegment)


# @@protoc_insertion_point(module_scope)
