# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeseries.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timeseries.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10timeseries.proto\"\xfd\x01\n\x07Segment\x12\x0f\n\x07startTs\x18\x01 \x01(\x04\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08lastUsed\x18\x03 \x01(\x04\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x14\n\x0csamplePeriod\x18\x05 \x01(\x01\x12\x1d\n\x15requestedSamplePeriod\x18\x06 \x01(\x01\x12\x11\n\tpageStart\x18\x07 \x01(\x04\x12\x10\n\x08isMinMax\x18\x08 \x01(\x08\x12\r\n\x05unitM\x18\t \x01(\x04\x12\x13\n\x0bsegmentType\x18\n \x01(\t\x12\x10\n\x08nrPoints\x18\x0b \x01(\x04\x12\x10\n\x04\x64\x61ta\x18\x0c \x03(\x01\x42\x02\x10\x01\x12\x0f\n\x07pageEnd\x18\r \x01(\x04\"b\n\x11TimeSeriesMessage\x12\x19\n\x07segment\x18\x03 \x01(\x0b\x32\x08.Segment\x12\x16\n\x0etotalResponses\x18\x07 \x01(\x04\x12\x1a\n\x12responseSequenceId\x18\x08 \x01(\x04\"$\n\x05\x44\x61tum\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x01\"0\n\x0c\x43hannelChunk\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x06.Datum\"0\n\rChunkResponse\x12\x1f\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\r.ChannelChunk\"3\n\x0cStateMessage\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"l\n\x17\x41gentTimeSeriesResponse\x12\x1e\n\x05state\x18\x01 \x01(\x0b\x32\r.StateMessageH\x00\x12\x1f\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x0e.ChunkResponseH\x00\x42\x10\n\x0eresponse_oneofb\x06proto3')
)




_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startTs', full_name='Segment.startTs', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='Segment.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastUsed', full_name='Segment.lastUsed', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='Segment.unit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samplePeriod', full_name='Segment.samplePeriod', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestedSamplePeriod', full_name='Segment.requestedSamplePeriod', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageStart', full_name='Segment.pageStart', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isMinMax', full_name='Segment.isMinMax', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unitM', full_name='Segment.unitM', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segmentType', full_name='Segment.segmentType', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nrPoints', full_name='Segment.nrPoints', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Segment.data', index=11,
      number=12, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageEnd', full_name='Segment.pageEnd', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=274,
)


_TIMESERIESMESSAGE = _descriptor.Descriptor(
  name='TimeSeriesMessage',
  full_name='TimeSeriesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='TimeSeriesMessage.segment', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalResponses', full_name='TimeSeriesMessage.totalResponses', index=1,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseSequenceId', full_name='TimeSeriesMessage.responseSequenceId', index=2,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=374,
)


_DATUM = _descriptor.Descriptor(
  name='Datum',
  full_name='Datum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Datum.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Datum.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=412,
)


_CHANNELCHUNK = _descriptor.Descriptor(
  name='ChannelChunk',
  full_name='ChannelChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ChannelChunk.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ChannelChunk.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=462,
)


_CHUNKRESPONSE = _descriptor.Descriptor(
  name='ChunkResponse',
  full_name='ChunkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='ChunkResponse.channels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=512,
)


_STATEMESSAGE = _descriptor.Descriptor(
  name='StateMessage',
  full_name='StateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='StateMessage.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='StateMessage.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=565,
)


_AGENTTIMESERIESRESPONSE = _descriptor.Descriptor(
  name='AgentTimeSeriesResponse',
  full_name='AgentTimeSeriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='AgentTimeSeriesResponse.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='AgentTimeSeriesResponse.chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response_oneof', full_name='AgentTimeSeriesResponse.response_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=567,
  serialized_end=675,
)

_TIMESERIESMESSAGE.fields_by_name['segment'].message_type = _SEGMENT
_CHANNELCHUNK.fields_by_name['data'].message_type = _DATUM
_CHUNKRESPONSE.fields_by_name['channels'].message_type = _CHANNELCHUNK
_AGENTTIMESERIESRESPONSE.fields_by_name['state'].message_type = _STATEMESSAGE
_AGENTTIMESERIESRESPONSE.fields_by_name['chunk'].message_type = _CHUNKRESPONSE
_AGENTTIMESERIESRESPONSE.oneofs_by_name['response_oneof'].fields.append(
  _AGENTTIMESERIESRESPONSE.fields_by_name['state'])
_AGENTTIMESERIESRESPONSE.fields_by_name['state'].containing_oneof = _AGENTTIMESERIESRESPONSE.oneofs_by_name['response_oneof']
_AGENTTIMESERIESRESPONSE.oneofs_by_name['response_oneof'].fields.append(
  _AGENTTIMESERIESRESPONSE.fields_by_name['chunk'])
_AGENTTIMESERIESRESPONSE.fields_by_name['chunk'].containing_oneof = _AGENTTIMESERIESRESPONSE.oneofs_by_name['response_oneof']
DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
DESCRIPTOR.message_types_by_name['TimeSeriesMessage'] = _TIMESERIESMESSAGE
DESCRIPTOR.message_types_by_name['Datum'] = _DATUM
DESCRIPTOR.message_types_by_name['ChannelChunk'] = _CHANNELCHUNK
DESCRIPTOR.message_types_by_name['ChunkResponse'] = _CHUNKRESPONSE
DESCRIPTOR.message_types_by_name['StateMessage'] = _STATEMESSAGE
DESCRIPTOR.message_types_by_name['AgentTimeSeriesResponse'] = _AGENTTIMESERIESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENT,
  __module__ = 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:Segment)
  ))
_sym_db.RegisterMessage(Segment)

TimeSeriesMessage = _reflection.GeneratedProtocolMessageType('TimeSeriesMessage', (_message.Message,), dict(
  DESCRIPTOR = _TIMESERIESMESSAGE,
  __module__ = 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:TimeSeriesMessage)
  ))
_sym_db.RegisterMessage(TimeSeriesMessage)

Datum = _reflection.GeneratedProtocolMessageType('Datum', (_message.Message,), dict(
  DESCRIPTOR = _DATUM,
  __module__ = 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:Datum)
  ))
_sym_db.RegisterMessage(Datum)

ChannelChunk = _reflection.GeneratedProtocolMessageType('ChannelChunk', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELCHUNK,
  __module__ = 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:ChannelChunk)
  ))
_sym_db.RegisterMessage(ChannelChunk)

ChunkResponse = _reflection.GeneratedProtocolMessageType('ChunkResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHUNKRESPONSE,
  __module__ = 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:ChunkResponse)
  ))
_sym_db.RegisterMessage(ChunkResponse)

StateMessage = _reflection.GeneratedProtocolMessageType('StateMessage', (_message.Message,), dict(
  DESCRIPTOR = _STATEMESSAGE,
  __module__ = 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:StateMessage)
  ))
_sym_db.RegisterMessage(StateMessage)

AgentTimeSeriesResponse = _reflection.GeneratedProtocolMessageType('AgentTimeSeriesResponse', (_message.Message,), dict(
  DESCRIPTOR = _AGENTTIMESERIESRESPONSE,
  __module__ = 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:AgentTimeSeriesResponse)
  ))
_sym_db.RegisterMessage(AgentTimeSeriesResponse)


_SEGMENT.fields_by_name['data'].has_options = True
_SEGMENT.fields_by_name['data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
